services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: gator
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gator
    ports:
      - "5432:5432"
    volumes:
      - gator_data:/var/lib/postgresql/data

volumes:
  gator_data:
